server:
  port: ${GATEWAY_SERVICE_PORT:8090}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8762/eureka/}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
