server:
  port: ${DISCOVERY_SERVICE_PORT:8762}

spring:
  application:
    name: discovery-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8762/eureka/}
    register-with-eureka: false
    renewalIntervalInSecs: 30
    registryFetchIntervalSeconds: 10
    fetch-registry: false
    server:
      enable-self-preservation: false