spring:
  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    flyway:
      enabled: false

server:
  port: ${SONG_SERVER_PORT:8082}
