spring:
  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    flyway:
      enabled: false
  application:
    name: song-service

server:
  port: ${SONG_SERVICE_PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8762/eureka/}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
