spring:
  datasource:
    url: jdbc:postgresql://${SONG_DB_HOST:localhost}:${SONG_DB_PORT:5432}/${SONG_DB_NAME:song_service}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: ${SONG_SERVER_PORT:8082}
