spring:
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5434/resource_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    flyway:
      enabled: false
  application:
    name: resource-service

server:
  port: ${RESOURCE_SERVICE_PORT:8081}

song:
  service:
    url: lb://song-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8762/eureka/}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}