spring:
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5434/resource_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    flyway:
      enabled: false

server:
  port: ${RESOURCE_SERVER_PORT:8081}

song:
  service:
    url: http://${SONG_SERVICE_HOST:localhost}:${SONG_SERVICE_PORT:8082}