spring:
  datasource:
    url: jdbc:postgresql://${RESOURCE_DB_HOST:localhost}:${RESOURCE_DB_PORT:5432}/${RESOURCE_DB_NAME:resource_service}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: ${RESOURCE_SERVER_PORT:8081}

song:
  service:
    url: http://${SONG_SERVICE_HOST:localhost}:${SONG_SERVICE_PORT:8082}